# Generated by Django 3.1.7 on 2021-12-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20211214_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(default='Not Specified', max_length=64),
        ),
    ]
