# Generated by Django 3.1.7 on 2021-12-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='Not Specified', max_length=64),
        ),
    ]
